name: Slack Notification Action 
description: Sends a notification to a Slack channel. 
inputs: 
slack-webhook: 
description: 'Slack webhook URL' 
required: true 
message: 
description: 'Notification message content' 
required: true 
channel: 
description: 'Slack channel to send the notification to' 
required: true 
runs: 
using: 'node20' 
main: 'index.js' 
